{{ $fullname := include "pastefy.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ .host }}
      secretName: {{ .tls.name }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-pastefy
                port:
                  number: {{ $.Values.service.pastefy.port }}
  {{- end }}