apiVersion: v1
kind: PersistentVolume
metadata:
  name: pastefy-db-pv
spec:
  capacity:
    storage: {{ .Values.mysql.storage.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mysql.storage.className }}
  hostPath:
    path: /opt/docker-volumes/pastify/dbvol