apiVersion: v1
kind: Service
metadata:
  name: {{ include "pastefy.fullname" . }}-mysql
  labels:
    {{- include "pastefy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.mysql.type }}
  ports:
    - port: {{ .Values.service.mysql.port }}
      targetPort: {{ .Values.service.mysql.port }}
  selector:
    app: mysql
